# Generated by Django 2.1.7 on 2019-05-13 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0002_ramo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ramo',
            old_name='nombre',
            new_name='nombre_ramo',
        ),
    ]
