# Generated by Django 2.1.7 on 2019-05-13 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0003_auto_20190513_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='numero',
        ),
    ]
