# Generated by Django 2.1.7 on 2019-05-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0004_remove_estudiante_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='apodo2',
            field=models.CharField(default='apodo1111', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiante',
            name='numero',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
